import { Award, BookOpen, Coins, LockKeyhole, ShieldCheck } from "lucide-react";
import { MetricCard } from "../components/MetricCard";
import { PageHeader } from "../components/PageHeader";
import { ProgressBar } from "../components/ProgressBar";
import { ProgressionFlow } from "../components/ProgressionFlow";
import { StatusBadge } from "../components/StatusBadge";
import { academyLearnerExperienceService } from "../services/academyLearnerExperienceService";
import { formatNeurons } from "../utils/format";

export function ProgressEngine() {
  const preview = academyLearnerExperienceService.getDashboardPreview();
  const completion = Math.round((preview.summary.completedPreviewCourses / Math.max(preview.courses.length, 1)) * 100);
  return <><PageHeader eyebrow="Knowledge progression" title="Progress Engine" description="Learning, assessment, PoK readiness, recognition, and ecosystem unlocks are tracked as one connected protocol." /><section className="academy-card p-5 sm:p-6"><ProgressionFlow activeStage={1} /><div className="mt-7"><ProgressBar value={completion} label="Formation completion across active records" tone="teal" /></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BookOpen} label="Completed previews" value={preview.summary.completedPreviewCourses} detail={`${preview.summary.activePreviewCourses} active records`} /><MetricCard icon={ShieldCheck} tone="teal" label="PoK eligible" value={preview.summary.eligibleRecognitionPreviews} detail="Knowledge validation met" /><MetricCard icon={Coins} label="Unlocked points" value={formatNeurons(preview.summary.totalUnlockedPreviewPoints)} detail="Local preview accounting" /><MetricCard icon={LockKeyhole} tone="violet" label="Pending points" value={formatNeurons(preview.summary.totalPendingPreviewPoints)} detail="Held behind protocol gates" /></section><section className="academy-card p-5"><p className="academy-label">Formation records</p><h2 className="mt-1 text-lg font-semibold text-white">Progress by course protocol</h2><div className="mt-5 grid gap-4">{preview.courses.map((course) => <article key={course.courseId} className="academy-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">{course.displayTitle}</p><p className="mt-1 text-xs text-slate-500">{course.previewPointTier} · {course.certificateLabel}</p></div><div className="flex flex-wrap gap-2"><StatusBadge label={course.progressState} /><StatusBadge label={course.assessmentState} /></div></div><div className="mt-5 grid gap-4 md:grid-cols-3"><ProgressBar value={course.contentProgress} label="Learning" /><ProgressBar value={course.assessmentScore ?? 0} label="Assessment" tone="amber" /><ProgressBar value={course.unlockedPreviewPoints === 0 ? 0 : Math.round((course.unlockedPreviewPoints / Math.max(course.unlockedPreviewPoints + course.pendingPreviewPoints, 1)) * 100)} label="Unlocks" tone="violet" /></div><div className="mt-4 flex items-center gap-2 border-t border-academy-line pt-4 text-sm text-slate-400"><Award size={16} className="text-violet-300" /><span>{course.recognitionLabel}</span></div></article>)}</div></section></>;
}
