import { Award, BookOpen, LockKeyhole, ShieldCheck, SquareCheckBig } from "lucide-react";
import { academyData } from "../services/academyData";
import { academyLearnerExperienceService } from "../services/academyLearnerExperienceService";
import { MetricCard } from "../components/MetricCard";
import { PageHeader } from "../components/PageHeader";
import { ProgressBar } from "../components/ProgressBar";
import { ProgressionFlow } from "../components/ProgressionFlow";
import { StatusBadge } from "../components/StatusBadge";

export function ProofOfKnowledge() {
  const preview = academyLearnerExperienceService.getDashboardPreview();
  return <><PageHeader eyebrow="Evidence protocol" title="Proof of Knowledge" description="Readiness combines completed learning evidence, deterministic assessment thresholds, and recognition requirements." /><section className="academy-card grid gap-6 p-5 sm:p-6 lg:grid-cols-[220px_1fr]"><div className="relative grid h-44 w-44 place-items-center self-center justify-self-center rounded-full" style={{ background: `conic-gradient(var(--academy-cyan) ${academyData.student.pokReadiness}%, #1d3145 0)` }}><div className="grid h-[140px] w-[140px] place-items-center rounded-full bg-academy-panel text-center"><div><ShieldCheck className="mx-auto text-teal-300" size={25} /><p className="academy-value mt-2 text-3xl text-white">{academyData.student.pokReadiness}%</p><p className="text-xs text-slate-400">Readiness</p></div></div></div><div className="min-w-0 self-center"><p className="academy-label">Connected progression</p><h2 className="mt-1 text-xl font-semibold text-white">Knowledge must be demonstrated before recognition</h2><p className="mt-2 text-sm leading-6 text-slate-400">Content consumption advances learning evidence. Assessments validate comprehension; recognition and ecosystem unlocks remain gated until their requirements are met.</p><div className="mt-6"><ProgressionFlow activeStage={1} /></div></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BookOpen} label="Active courses" value={preview.summary.activePreviewCourses} detail="Learning evidence in progress" /><MetricCard icon={SquareCheckBig} tone="amber" label="Assessments passed" value={preview.courses.filter((course) => course.assessmentState === "passed").length} detail="Deterministic preview results" /><MetricCard icon={Award} tone="violet" label="Recognition eligible" value={preview.summary.eligibleRecognitionPreviews} detail="Preview eligibility only" /><MetricCard icon={LockKeyhole} label="Pending points" value={preview.summary.totalPendingPreviewPoints} detail="Held behind knowledge gates" /></section><section className="academy-card p-5"><p className="academy-label">Course evidence</p><h2 className="mt-1 text-lg font-semibold text-white">Readiness by formation protocol</h2><div className="mt-5 grid gap-3">{preview.courses.map((course) => <article key={course.courseId} className="academy-surface grid gap-4 p-4 lg:grid-cols-[1fr_1fr_auto] lg:items-center"><div><p className="font-semibold text-white">{course.displayTitle}</p><p className="mt-1 text-xs text-slate-500">{course.previewPointTier} · threshold {course.assessmentThreshold}%</p></div><ProgressBar value={course.contentProgress} label="Learning evidence" tone={course.previewPointTier === "Applied Preview" ? "violet" : "blue"} /><div className="flex flex-wrap gap-2"><StatusBadge label={course.assessmentState} /><StatusBadge label={course.recognitionStatus} /></div></article>)}</div></section></>;
}
